/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Event;
import java.awt.Font;
import java.awt.event.KeyEvent;
import javafx.scene.input.KeyCode;
import javax.swing.BorderFactory;

/**
 *
 * @author JoseM
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btGravar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbCodigo = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        lbApelido = new javax.swing.JLabel();
        tfApelido = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        lbNome = new javax.swing.JLabel();
        lbDataNasc = new javax.swing.JLabel();
        lbBI = new javax.swing.JLabel();
        tfBI = new javax.swing.JTextField();
        lbSexo = new javax.swing.JLabel();
        rdMasc = new javax.swing.JRadioButton();
        rdFemin = new javax.swing.JRadioButton();
        lbNaturalidade = new javax.swing.JLabel();
        tfNaturalidade = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        lbContactos = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbMovel = new javax.swing.JLabel();
        lbFixo = new javax.swing.JLabel();
        tfMovel = new javax.swing.JTextField();
        tfFixo = new javax.swing.JTextField();
        lbEstadoC = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lbEndereco = new javax.swing.JLabel();
        tfEndereco = new javax.swing.JTextField();
        lbSalario = new javax.swing.JLabel();
        tfSalario = new javax.swing.JTextField();
        lbObservacao = new javax.swing.JLabel();
        tfObservacao = new javax.swing.JTextField();
        formatedTfData = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        btGravar.setText("Gravar");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(342, Short.MAX_VALUE)
                .addComponent(btGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        lbCodigo.setText("Código");
        lbCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbCodigoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbCodigoMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 25, 0, 0);
        jPanel3.add(lbCodigo, gridBagConstraints);

        tfCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        tfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigoActionPerformed(evt);
            }
        });
        tfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCodigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCodigoKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 119;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 0, 0);
        jPanel3.add(tfCodigo, gridBagConstraints);

        lbApelido.setText("Apelido");
        lbApelido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbApelidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbApelidoMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 149;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 25, 0, 0);
        jPanel3.add(lbApelido, gridBagConstraints);

        tfApelido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        tfApelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfApelidoActionPerformed(evt);
            }
        });
        tfApelido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfApelidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfApelidoKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 220;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 0, 0);
        jPanel3.add(tfApelido, gridBagConstraints);

        tfNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });
        tfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNomeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNomeKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 220;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 0, 0);
        jPanel3.add(tfNome, gridBagConstraints);

        lbNome.setText("Nome Completo");
        lbNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbNomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbNomeMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 0, 0);
        jPanel3.add(lbNome, gridBagConstraints);

        lbDataNasc.setText("Data de Nascimento[dd/mm/aa]");
        lbDataNasc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbDataNascMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbDataNascMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 23, 0, 0);
        jPanel3.add(lbDataNasc, gridBagConstraints);

        lbBI.setText("Numero de BI");
        lbBI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbBIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbBIMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 107;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 0, 0);
        jPanel3.add(lbBI, gridBagConstraints);

        tfBI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        tfBI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBIActionPerformed(evt);
            }
        });
        tfBI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfBIKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfBIKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 220;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 0, 0);
        jPanel3.add(tfBI, gridBagConstraints);

        lbSexo.setText("Sexo");
        lbSexo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbSexoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbSexoMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 121;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 57, 0, 0);
        jPanel3.add(lbSexo, gridBagConstraints);

        buttonGroup1.add(rdMasc);
        rdMasc.setText("Masculino");
        rdMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdMascActionPerformed(evt);
            }
        });
        rdMasc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rdMascKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 57, 0, 0);
        jPanel3.add(rdMasc, gridBagConstraints);

        buttonGroup1.add(rdFemin);
        rdFemin.setText("Feminino");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 18, 0, 0);
        jPanel3.add(rdFemin, gridBagConstraints);

        lbNaturalidade.setText("Naturalidade");
        lbNaturalidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbNaturalidadeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbNaturalidadeMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 57, 0, 0);
        jPanel3.add(lbNaturalidade, gridBagConstraints);

        tfNaturalidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        tfNaturalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNaturalidadeActionPerformed(evt);
            }
        });
        tfNaturalidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNaturalidadeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNaturalidadeKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 220;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 57, 0, 0);
        jPanel3.add(tfNaturalidade, gridBagConstraints);

        lbEmail.setText("E-mail");
        lbEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbEmailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbEmailMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 198;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 57, 0, 0);
        jPanel3.add(lbEmail, gridBagConstraints);

        tfEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });
        tfEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfEmailKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 220;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 57, 0, 0);
        jPanel3.add(tfEmail, gridBagConstraints);

        lbContactos.setText("Contactos");
        lbContactos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbContactosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbContactosMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 177;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 57, 0, 0);
        jPanel3.add(lbContactos, gridBagConstraints);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lbMovel.setText("Móvel:");
        lbMovel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMovelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMovelMouseExited(evt);
            }
        });

        lbFixo.setText("Fixo:");
        lbFixo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbFixoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbFixoMouseExited(evt);
            }
        });

        tfMovel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        tfMovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMovelActionPerformed(evt);
            }
        });
        tfMovel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfMovelKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfMovelKeyTyped(evt);
            }
        });

        tfFixo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        tfFixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFixoActionPerformed(evt);
            }
        });
        tfFixo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfFixoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfFixoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMovel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfMovel, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(tfFixo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMovel)
                    .addComponent(tfMovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFixo)
                    .addComponent(tfFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipady = -4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 57, 0, 24);
        jPanel3.add(jPanel5, gridBagConstraints);

        lbEstadoC.setText("Estado Civil");
        lbEstadoC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbEstadoCMouseEntered1(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbEstadoCMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 118;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 0, 0);
        jPanel3.add(lbEstadoC, gridBagConstraints);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Casado", "Divorciado", "Viuvo" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 0, 0);
        jPanel3.add(jComboBox1, gridBagConstraints);

        lbEndereco.setText("Endereço");
        lbEndereco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbEnderecoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbEnderecoMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 129;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 0, 0);
        jPanel3.add(lbEndereco, gridBagConstraints);

        tfEndereco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        tfEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEnderecoActionPerformed(evt);
            }
        });
        tfEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfEnderecoKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 220;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 41, 0);
        jPanel3.add(tfEndereco, gridBagConstraints);

        lbSalario.setText("Salário");
        lbSalario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbSalarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbSalarioMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 194;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 57, 0, 0);
        jPanel3.add(lbSalario, gridBagConstraints);

        tfSalario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        tfSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSalarioActionPerformed(evt);
            }
        });
        tfSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSalarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfSalarioKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 220;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 57, 0, 0);
        jPanel3.add(tfSalario, gridBagConstraints);

        lbObservacao.setText("Observação");
        lbObservacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbObservacaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbObservacaoMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 168;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 57, 0, 0);
        jPanel3.add(lbObservacao, gridBagConstraints);

        tfObservacao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        tfObservacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfObservacaoActionPerformed(evt);
            }
        });
        tfObservacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfObservacaoKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 220;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 57, 41, 0);
        jPanel3.add(tfObservacao, gridBagConstraints);

        formatedTfData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        formatedTfData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/M/yy"))));
        formatedTfData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formatedTfDataKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formatedTfDataKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 220;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 0, 0);
        jPanel3.add(formatedTfData, gridBagConstraints);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoActionPerformed

    private void tfApelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfApelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfApelidoActionPerformed

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void tfBIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBIActionPerformed

    private void rdMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdMascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdMascActionPerformed

    private void tfNaturalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNaturalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNaturalidadeActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void tfEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEnderecoActionPerformed

    private void tfSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSalarioActionPerformed

    private void tfObservacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfObservacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfObservacaoActionPerformed

    private void tfNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeKeyTyped
        // TODO add your handling code here:
        
        char caracter = evt.getKeyChar();
        
        validaNomes(evt, caracter);
        /*
        if (((caracter < 'A') || (caracter > 'z'))
                        && (caracter != '\b') && (caracter != ' ')) {
                    evt.consume();
                }*/
    }//GEN-LAST:event_tfNomeKeyTyped

    private void tfApelidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfApelidoKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        
        validaNomes(evt, caracter);
        /*
        if (((caracter < 'A') || (caracter > 'z'))
                        && (caracter != '\b') && (caracter != ' ')) {
                    evt.consume();
                }*/
    }//GEN-LAST:event_tfApelidoKeyTyped

    private void formatedTfDataKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formatedTfDataKeyTyped
        // TODO add your handling code here:
        
        char caracter = evt.getKeyChar();
        
        if (((caracter < '0') || (caracter > '9'))
                        && (caracter != '\b') && (caracter != '/')) {
                    evt.consume();
                }
    }//GEN-LAST:event_formatedTfDataKeyTyped

    private void tfFixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFixoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFixoActionPerformed

    private void tfMovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMovelActionPerformed

    private void tfBIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBIKeyTyped
        // TODO add your handling code here:
        
        char caracter = evt.getKeyChar();
        
        
        if (tfBI.getText().length()<12) {
            if (((caracter < '0') || (caracter > '9'))
                        && (caracter != '\b')) {
                    evt.consume();
                } 
        }
        if(tfBI.getText().length()>=13) {
            
                    evt.consume();   
        }
        if (tfBI.getText().length()>=12) {
            if (((caracter < 'A') || (caracter > 'z'))
                        && (caracter != '\b')) {
                    evt.consume();
                } 
        }
        
        
    }//GEN-LAST:event_tfBIKeyTyped

    private void tfMovelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMovelKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        
         if (tfMovel.getText().length()<1) {
            if (((caracter < '8') || (caracter > '8'))
                        && (caracter != '\b')) {
                    evt.consume();
                } 
        }
        if (tfMovel.getText().length()==1) {
            if (((caracter < '2') || (caracter > '7'))
                        && (caracter != '\b')) {
                    evt.consume();
                } 
        }
        if (((caracter < '0') || (caracter > '9'))
                        && (caracter != '\b')) {
                    evt.consume();
                }
        
        if (tfMovel.getText().length()>8) {
            
                    evt.consume();
                
        }
    }//GEN-LAST:event_tfMovelKeyTyped

    private void tfNaturalidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNaturalidadeKeyTyped
        // TODO add your handling code here:
        
        char caracter= evt.getKeyChar();
        
        validaNomes(evt, caracter);
    }//GEN-LAST:event_tfNaturalidadeKeyTyped

    private void tfFixoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFixoKeyTyped
        // TODO add your handling code here:
        
        char caracter = evt.getKeyChar();
        
         if (tfFixo.getText().length()<1) {
            if (((caracter < '2') || (caracter > '2'))
                        && (caracter != '\b')) {
                    evt.consume();
                } 
        }
        
        if (((caracter < '0') || (caracter > '9'))
                        && (caracter != '\b')) {
                    evt.consume();
                }
        
        if (tfFixo.getText().length()>7) {
            
                    evt.consume();
                
        }
        
    }//GEN-LAST:event_tfFixoKeyTyped

    private void tfSalarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSalarioKeyTyped
        // TODO add your handling code here:
        char caracter=evt.getKeyChar();
        
        if (((caracter < '0') || (caracter > '9'))
                        && (caracter != '\b') && (caracter != '.')) {
                    evt.consume();
                }
    }//GEN-LAST:event_tfSalarioKeyTyped

    private void tfCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodigoKeyPressed
        // TODO add your handling code here:
        int caracter=evt.getKeyCode();
        
        if ((caracter == KeyEvent.VK_ENTER)
                        && (caracter != '\b')) {
                    tfApelido.requestFocus();
                } 
        
        
    }//GEN-LAST:event_tfCodigoKeyPressed

    private void tfApelidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfApelidoKeyPressed
        // TODO add your handling code here:
        int caracter=evt.getKeyCode();
        
        if ((caracter == KeyEvent.VK_ENTER)
                        && (caracter != '\b')) {
                    tfNome.requestFocus();
                } 
        
        
    }//GEN-LAST:event_tfApelidoKeyPressed

    private void tfNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeKeyPressed
        // TODO add your handling code here:
        int caracter=evt.getKeyCode();
        
        if ((caracter == KeyEvent.VK_ENTER)
                        && (caracter != '\b')) {
                    formatedTfData.requestFocus();
                } 
        
        
    }//GEN-LAST:event_tfNomeKeyPressed

    private void formatedTfDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formatedTfDataKeyPressed
        // TODO add your handling code here:
       int caracter=evt.getKeyCode();
        
        if ((caracter == KeyEvent.VK_ENTER)
                        && (caracter != '\b')) {
                    tfBI.requestFocus();
                } 
         
    }//GEN-LAST:event_formatedTfDataKeyPressed

    private void tfBIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBIKeyPressed
        // TODO add your handling code here:
        
        int caracter=evt.getKeyCode();
        
        if ((caracter == KeyEvent.VK_ENTER)
                        && (caracter != '\b')) {
                    tfEndereco.requestFocus();
                } 
        
    }//GEN-LAST:event_tfBIKeyPressed

    private void tfEnderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEnderecoKeyPressed
        // TODO add your handling code here:
        int caracter=evt.getKeyCode();
        
        if ((caracter == KeyEvent.VK_ENTER)
                        && (caracter != '\b')) {
                    rdMasc.requestFocus();
                } 
        
    }//GEN-LAST:event_tfEnderecoKeyPressed

    private void rdMascKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rdMascKeyPressed
        // TODO add your handling code here:
        
        int caracter=evt.getKeyCode();
        
        if ((caracter == KeyEvent.VK_ENTER)
                        && (caracter != '\b')) {
                    tfNaturalidade.requestFocus();
                } 
        
    }//GEN-LAST:event_rdMascKeyPressed

    private void tfNaturalidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNaturalidadeKeyPressed
        // TODO add your handling code here:
        int caracter=evt.getKeyCode();
        
        if ((caracter == KeyEvent.VK_ENTER)
                        && (caracter != '\b')) {
                    tfEmail.requestFocus();
                } 
        
    }//GEN-LAST:event_tfNaturalidadeKeyPressed

    private void tfEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEmailKeyPressed
        // TODO add your handling code here:
        
        int caracter=evt.getKeyCode();
        
        if ((caracter == KeyEvent.VK_ENTER)
                        && (caracter != '\b')) {
                    tfMovel.requestFocus();
                } 
        
    }//GEN-LAST:event_tfEmailKeyPressed

    private void tfMovelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMovelKeyPressed
        // TODO add your handling code here:
        int caracter=evt.getKeyCode();
        
        if ((caracter == KeyEvent.VK_ENTER)
                        && (caracter != '\b')) {
                    tfFixo.requestFocus();
                } 
        
    }//GEN-LAST:event_tfMovelKeyPressed

    private void tfFixoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFixoKeyPressed
        // TODO add your handling code here:
        
        int caracter=evt.getKeyCode();
        
        if ((caracter == KeyEvent.VK_ENTER)
                        && (caracter != '\b')) {
                    tfSalario.requestFocus();
                } 
        
    }//GEN-LAST:event_tfFixoKeyPressed

    private void tfSalarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSalarioKeyPressed
        // TODO add your handling code here:
        
        int caracter=evt.getKeyCode();
        
        if ((caracter == KeyEvent.VK_ENTER)
                        && (caracter != '\b')) {
                    tfObservacao.requestFocus();
                } 
        
    }//GEN-LAST:event_tfSalarioKeyPressed

    private void tfObservacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfObservacaoKeyPressed
        // TODO add your handling code here:
        
        int caracter=evt.getKeyCode();
        
        if ((caracter == KeyEvent.VK_ENTER)
                        && (caracter != '\b')) {
                    btGravar.requestFocus();
                } 
        
    }//GEN-LAST:event_tfObservacaoKeyPressed

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        // TODO add your handling code here:
        
        if(tfSalario.getText().length()<=0){     
            tfSalario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
            tfSalario.requestFocus();
        }else tfSalario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        
        
        if(tfFixo.getText().length()<=0){     
            tfFixo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
            tfFixo.requestFocus();
        }else tfFixo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        
        
        if(tfMovel.getText().length()<=0){     
            tfMovel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
            tfMovel.requestFocus();
        }else tfMovel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        
        
        if(tfEmail.getText().length()<=0){     
            tfEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
            tfEmail.requestFocus();
        }else tfEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        
        
        if(tfNaturalidade.getText().length()<=0){     
            tfNaturalidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
            tfNaturalidade.requestFocus();
        }else tfNaturalidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        
        
        if(tfEndereco.getText().length()<=0){     
            tfEndereco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
            tfEndereco.requestFocus();
        }else tfEndereco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        
        
        if(tfBI.getText().length()<=0){     
            tfBI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
            tfBI.requestFocus();
        }else tfBI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        
        
        if(formatedTfData.getText().length()<=0){     
            formatedTfData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
            formatedTfData.requestFocus();
        }else formatedTfData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        
        
        if(tfNome.getText().length()<=0){     
            tfNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
            tfNome.requestFocus();
        }else tfNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        
        
        if(tfApelido.getText().length()<=0){     
            tfApelido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
            tfApelido.requestFocus();
        }else tfApelido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        
        if(tfCodigo.getText().length()<=0){     
            tfCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
            tfCodigo.requestFocus();
        }else tfCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
            
       
    }//GEN-LAST:event_btGravarActionPerformed

    private void tfCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodigoKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        
        
        if (tfCodigo.getText().length()<12) {
            if (((caracter < '0') || (caracter > '9'))
                        && (caracter != '\b')) {
                    evt.consume();
                } 
        }
        if (tfCodigo.getText().length()>=12) {
            
                    evt.consume();
                
        }
    }//GEN-LAST:event_tfCodigoKeyTyped

    private void lbCodigoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCodigoMouseEntered
        // TODO add your handling code here:
       lbCodigo.setFont(new Font("Tahoma", 1, 11));
    }//GEN-LAST:event_lbCodigoMouseEntered

    private void lbApelidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbApelidoMouseEntered
        // TODO add your handling code here:
        lbApelido.setFont(new Font("Tahoma", 1, 11));
    }//GEN-LAST:event_lbApelidoMouseEntered

    private void lbNomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNomeMouseEntered
        // TODO add your handling code here:
        lbNome.setFont(new Font("Tahoma", 1, 11));
    }//GEN-LAST:event_lbNomeMouseEntered

    private void lbDataNascMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDataNascMouseEntered
        // TODO add your handling code here:
        lbDataNasc.setFont(new Font("Tahoma", 1, 11));
    }//GEN-LAST:event_lbDataNascMouseEntered

    private void lbBIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBIMouseEntered
        // TODO add your handling code here:
        lbBI.setFont(new Font("Tahoma", 1, 11));
    }//GEN-LAST:event_lbBIMouseEntered

    private void lbEstadoCMouseEntered1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEstadoCMouseEntered1
        // TODO add your handling code here:
        lbEstadoC.setFont(new Font("Tahoma", 1, 11));
    }//GEN-LAST:event_lbEstadoCMouseEntered1

    private void lbEnderecoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEnderecoMouseEntered
        // TODO add your handling code here:
        lbEndereco.setFont(new Font("Tahoma", 1, 11));
    }//GEN-LAST:event_lbEnderecoMouseEntered

    private void lbSexoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSexoMouseEntered
        // TODO add your handling code here:
        lbSexo.setFont(new Font("Tahoma", 1, 11));
    }//GEN-LAST:event_lbSexoMouseEntered

    private void lbNaturalidadeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNaturalidadeMouseEntered
        // TODO add your handling code here:
        lbNaturalidade.setFont(new Font("Tahoma", 1, 11));
    }//GEN-LAST:event_lbNaturalidadeMouseEntered

    private void lbEmailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEmailMouseEntered
        // TODO add your handling code here:
        lbEmail.setFont(new Font("Tahoma", 1, 11));
    }//GEN-LAST:event_lbEmailMouseEntered

    private void lbContactosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbContactosMouseEntered
        // TODO add your handling code here:
        lbContactos.setFont(new Font("Tahoma", 1, 11));
    }//GEN-LAST:event_lbContactosMouseEntered

    private void lbMovelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMovelMouseEntered
        // TODO add your handling code here:
        lbMovel.setFont(new Font("Tahoma", 1, 11));
    }//GEN-LAST:event_lbMovelMouseEntered

    private void lbFixoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbFixoMouseEntered
        // TODO add your handling code here:
        lbFixo.setFont(new Font("Tahoma", 1, 11));
    }//GEN-LAST:event_lbFixoMouseEntered

    private void lbSalarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSalarioMouseEntered
        // TODO add your handling code here:
        lbSalario.setFont(new Font("Tahoma", 1, 11));
    }//GEN-LAST:event_lbSalarioMouseEntered

    private void lbObservacaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbObservacaoMouseEntered
        // TODO add your handling code here:
        lbObservacao.setFont(new Font("Tahoma", 1, 11));
    }//GEN-LAST:event_lbObservacaoMouseEntered

    private void lbCodigoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCodigoMouseExited
        // TODO add your handling code here:
        lbCodigo.setFont(new Font("Tahoma", 0, 11));
    }//GEN-LAST:event_lbCodigoMouseExited

    private void lbApelidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbApelidoMouseExited
        // TODO add your handling code here:
        lbApelido.setFont(new Font("Tahoma", 0, 11));
    }//GEN-LAST:event_lbApelidoMouseExited

    private void lbNomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNomeMouseExited
        // TODO add your handling code here:
        lbNome.setFont(new Font("Tahoma", 0, 11));
    }//GEN-LAST:event_lbNomeMouseExited

    private void lbDataNascMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDataNascMouseExited
        // TODO add your handling code here:
        lbDataNasc.setFont(new Font("Tahoma", 0, 11));
    }//GEN-LAST:event_lbDataNascMouseExited

    private void lbBIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBIMouseExited
        // TODO add your handling code here:
        lbBI.setFont(new Font("Tahoma", 0, 11));
    }//GEN-LAST:event_lbBIMouseExited

    private void lbEstadoCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEstadoCMouseExited
        // TODO add your handling code here:
        lbEstadoC.setFont(new Font("Tahoma", 0, 11));
    }//GEN-LAST:event_lbEstadoCMouseExited

    private void lbEnderecoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEnderecoMouseExited
        // TODO add your handling code here:
        lbEndereco.setFont(new Font("Tahoma", 0, 11));
    }//GEN-LAST:event_lbEnderecoMouseExited

    private void lbSexoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSexoMouseExited
        // TODO add your handling code here:
        lbSexo.setFont(new Font("Tahoma", 0, 11));
    }//GEN-LAST:event_lbSexoMouseExited

    private void lbNaturalidadeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNaturalidadeMouseExited
        // TODO add your handling code here:
        lbNaturalidade.setFont(new Font("Tahoma", 0, 11));
    }//GEN-LAST:event_lbNaturalidadeMouseExited

    private void lbEmailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEmailMouseExited
        // TODO add your handling code here:
        lbEmail.setFont(new Font("Tahoma", 0, 11));
    }//GEN-LAST:event_lbEmailMouseExited

    private void lbContactosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbContactosMouseExited
        // TODO add your handling code here:
        lbContactos.setFont(new Font("Tahoma", 0, 11));
    }//GEN-LAST:event_lbContactosMouseExited

    private void lbMovelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMovelMouseExited
        // TODO add your handling code here:
        lbMovel.setFont(new Font("Tahoma", 0, 11));
    }//GEN-LAST:event_lbMovelMouseExited

    private void lbFixoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbFixoMouseExited
        // TODO add your handling code here:
        lbFixo.setFont(new Font("Tahoma", 0, 11));
    }//GEN-LAST:event_lbFixoMouseExited

    private void lbSalarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSalarioMouseExited
        // TODO add your handling code here:
        lbSalario.setFont(new Font("Tahoma", 0, 11));
    }//GEN-LAST:event_lbSalarioMouseExited

    private void lbObservacaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbObservacaoMouseExited
        // TODO add your handling code here:
        lbObservacao.setFont(new Font("Tahoma", 0, 11));
    }//GEN-LAST:event_lbObservacaoMouseExited

    
    private void validaNomes(KeyEvent evt, char caracter){
        if (((caracter < 'A') || (caracter > 'z'))
                        && (caracter != '\b') && (caracter != ' ')) {
                    evt.consume();
                }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGravar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField formatedTfData;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbApelido;
    private javax.swing.JLabel lbBI;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbContactos;
    private javax.swing.JLabel lbDataNasc;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbEstadoC;
    private javax.swing.JLabel lbFixo;
    private javax.swing.JLabel lbMovel;
    private javax.swing.JLabel lbNaturalidade;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbObservacao;
    private javax.swing.JLabel lbSalario;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JRadioButton rdFemin;
    private javax.swing.JRadioButton rdMasc;
    private javax.swing.JTextField tfApelido;
    private javax.swing.JTextField tfBI;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfFixo;
    private javax.swing.JTextField tfMovel;
    private javax.swing.JTextField tfNaturalidade;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfObservacao;
    private javax.swing.JTextField tfSalario;
    // End of variables declaration//GEN-END:variables
}
